"""End-to-end test for Data Augmentation pipeline template"""
import pytest

from lib.llm_config import LLMConfigManager
from lib.templates import template_registry
from lib.workflow import Pipeline as WorkflowPipeline


@pytest.mark.integration
@pytest.mark.asyncio
async def test_data_augmentation_pipeline_e2e_real(e2e_storage):
    """
    e2e test for data augmentation pipeline with real ollama calls

    tests full pipeline: StructureSampler -> SemanticInfiller -> DuplicateRemover
    verifies:
    - pipeline execution completes successfully
    - correct number of results generated
    - result structure matches expectations
    - all blocks executed with valid traces
    - usage tracking works
    - embedding-based duplicate detection runs
    """
    # initialize llm config manager with test storage
    llm_config_manager = LLMConfigManager(e2e_storage)

    # monkey patch the global llm_config_manager
    import app

    original_manager = app.llm_config_manager
    app.llm_config_manager = llm_config_manager

    try:
        # get template
        template = template_registry.get_template("data_augmentation")
        assert template is not None, "data_augmentation template not found"

        # create pipeline from template
        pipeline_def = {"name": "Test Data Augmentation E2E", "blocks": template["blocks"]}
        pipeline = WorkflowPipeline.load_from_dict(pipeline_def)

        # create seed data with minimal records (1 seed for speed)
        seed_data = {
            "target_count": 1,  # minimal for fast e2e test
            "categorical_fields": ["category"],
            "numeric_fields": ["price"],
            "dependencies": {},  # no dependencies for this simple example
            "fields_to_generate": ["description", "price"],
            "comparison_fields": ["description"],
            "samples": [
                {"category": "electronics", "price": 299, "description": "Wireless noise-canceling headphones with premium sound quality"},
                {"category": "furniture", "price": 199, "description": "Ergonomic office chair with lumbar support"},
            ],
        }

        # execute pipeline (multiplier returns list of results)
        # this will make REAL calls to ollama
        print("\n🚀 Running e2e test with real LLM calls to Ollama...")
        results = await pipeline.execute(seed_data)

        # verify return type and structure
        assert isinstance(results, list), "Multiplier pipeline should return list"
        assert len(results) > 0, "Should generate at least one result"
        print(f"✅ Generated {len(results)} results")

        # verify result structure (ExecutionResult dataclass)
        first_result = results[0]
        assert hasattr(first_result, "result"), "Should be ExecutionResult dataclass"

        # extract fields from ExecutionResult
        result_data = first_result.result
        trace = first_result.trace
        trace_id = first_result.trace_id
        usage = first_result.usage

        # verify result has expected fields
        assert "category" in result_data, "Result should have category field"
        assert "price" in result_data, "Result should have price field"
        assert "description" in result_data, "Description should be generated by SemanticInfiller"

        # verify DuplicateRemover added fields
        assert "is_duplicate" in result_data, "DuplicateRemover should add is_duplicate flag"
        assert (
            "similarity_score" in result_data
        ), "DuplicateRemover should add similarity_score"
        assert isinstance(result_data["is_duplicate"], bool), "is_duplicate should be boolean"
        assert isinstance(
            result_data["similarity_score"], (int, float)
        ), "similarity_score should be numeric"
        print(f"✅ Result structure valid: {list(result_data.keys())}")

        # verify trace contains remaining blocks (StructureSampler runs separately for multiplier)
        assert len(trace) == 2, f"Should have 2 blocks in seed trace, got {len(trace)}"
        assert trace[0].block_type == "SemanticInfiller", "First block should be SemanticInfiller"
        assert trace[1].block_type == "DuplicateRemover", "Second block should be DuplicateRemover"
        print(f"✅ All seed processing blocks executed: {[t.block_type for t in trace]}")

        # verify usage tracking
        assert usage.input_tokens > 0, "Should have input tokens from LLM calls"
        assert usage.output_tokens > 0, "Should have output tokens from LLM calls"
        print(f"✅ Usage tracked: in={usage.input_tokens}, out={usage.output_tokens}")

        # verify trace_id exists
        assert trace_id is not None
        assert len(trace_id) > 0

        # verify generated content quality (basic sanity checks)
        description = result_data.get("description", "")
        assert len(description) > 0, "Generated description should not be empty"

        price = result_data.get("price")
        assert isinstance(price, (int, float)), "Generated price should be numeric"
        assert price > 0, "Generated price should be positive"

        print(f"\n✅ E2E test passed!")
        print(f"📊 Sample result: {result_data}")
        print(f"📈 Usage: in={usage.input_tokens}, out={usage.output_tokens}")

    finally:
        # restore original llm_config_manager
        app.llm_config_manager = original_manager


@pytest.mark.asyncio
async def test_data_augmentation_pipeline_missing_fields_error():
    """test that pipeline fails with clear error when required fields are missing"""
    template = template_registry.get_template("data_augmentation")
    assert template is not None

    pipeline_def = {"name": "Test Data Augmentation", "blocks": template["blocks"]}
    pipeline = WorkflowPipeline.load_from_dict(pipeline_def)

    # seed data missing required template variables
    seed_data = {
        "samples": [
            {"plan": "free", "role": "user", "storage": 10, "bio": "Casual user"},
        ]
    }

    # should fail with undefined variable error
    with pytest.raises(Exception) as exc_info:
        await pipeline.execute(seed_data)

    error_msg = str(exc_info.value)
    assert "undefined" in error_msg.lower() or "target_count" in error_msg
