name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  pre-merge:
    runs-on: ubuntu-latest
    # skip if PR is draft
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Python dependencies
        run: uv sync --all-extras

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: yarn install

      - name: Run pre-merge checks
        run: make pre-merge
